# Generated by Django 4.2.19 on 2025-04-03 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_image', models.ImageField(blank=True, null=True, upload_to='templates/pics/items-pics')),
                ('product_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(max_length=120, null=True)),
                ('discount', models.CharField(max_length=3, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('stock', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.FloatField(blank=True, default=0, null=True)),
                ('num_reviews', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
