# Generated by Django 4.2.23 on 2025-06-22 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_seller',
            new_name='is_host',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address3',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gst_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_description',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='wallet_balance',
        ),
    ]
